services:
  bmg-odoo-sync:
    image: python:3.11-slim
    container_name: bmg_sincronizador
    restart: always
    volumes:
      # --- RUTA ACTUALIZADA según configuración del NAS ---
      - /share/Public/AppPedidos/V2.0:/app
      
      # Mapeo de carpetas de archivos
      - /share/BMGLocalStorage:/originales
      - /share/Trabajos/LAD:/salida/LAD
      
    environment:
      - PYTHONUNBUFFERED=1
    # Mejora: Instalación de fuentes y limpieza de caracteres en logs
    entrypoint: >
      sh -c "apt-get update && apt-get install -y gcc libxml2-dev libxslt-dev python3-dev libmupdf-dev fontconfig fonts-dejavu &&
             cd /tmp && pip install --no-cache-dir zeep odoorpc pymupdf pypdf lxml python-barcode Pillow &&
             cd /app && 
             while true; do 
               echo '--- Iniciando ejecucion automatica ---'; 
               python -u 00_orquestador.py; 
               echo '--- Ciclo finalizado. Esperando 10 minutos... ---'; 
               sleep 600; 
             done"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
